UPDATE STATISTICS Account;
UPDATE STATISTICS Foodstuff;
UPDATE STATISTICS FoodstuffShoppingListItem;
UPDATE STATISTICS Ingredient;
UPDATE STATISTICS Recipe;
UPDATE STATISTICS RecipeShoppingListItem;
UPDATE STATISTICS SharedShoppingList;
UPDATE STATISTICS ShoppingList;